// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/custom_tool.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CustomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	JsonData      string                 `protobuf:"bytes,5,opt,name=JsonData,proto3" json:"JsonData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomRequest) Reset() {
	*x = CustomRequest{}
	mi := &file_proto_custom_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomRequest) ProtoMessage() {}

func (x *CustomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_custom_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomRequest.ProtoReflect.Descriptor instead.
func (*CustomRequest) Descriptor() ([]byte, []int) {
	return file_proto_custom_tool_proto_rawDescGZIP(), []int{0}
}

func (x *CustomRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CustomRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CustomRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CustomRequest) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

type CustomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomResponse) Reset() {
	*x = CustomResponse{}
	mi := &file_proto_custom_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomResponse) ProtoMessage() {}

func (x *CustomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_custom_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomResponse.ProtoReflect.Descriptor instead.
func (*CustomResponse) Descriptor() ([]byte, []int) {
	return file_proto_custom_tool_proto_rawDescGZIP(), []int{1}
}

func (x *CustomResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_custom_tool_proto protoreflect.FileDescriptor

const file_proto_custom_tool_proto_rawDesc = "" +
	"\n" +
	"\x17proto/custom_tool.proto\x12\x06custom\"\x89\x01\n" +
	"\rCustomRequest\x12\x12\n" +
	"\x04Kind\x18\x01 \x01(\tR\x04Kind\x12\x16\n" +
	"\x06Method\x18\x02 \x01(\tR\x06Method\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1c\n" +
	"\tNamespace\x18\x04 \x01(\tR\tNamespace\x12\x1a\n" +
	"\bJsonData\x18\x05 \x01(\tR\bJsonData\"(\n" +
	"\x0eCustomResponse\x12\x16\n" +
	"\x06Result\x18\x01 \x01(\tR\x06Result2R\n" +
	"\x11CustomToolService\x12=\n" +
	"\n" +
	"CustomTool\x12\x15.custom.CustomRequest\x1a\x16.custom.CustomResponse\"\x00B3Z1github.com/naveenthangaraj03/k8s-mcp-server/protob\x06proto3"

var (
	file_proto_custom_tool_proto_rawDescOnce sync.Once
	file_proto_custom_tool_proto_rawDescData []byte
)

func file_proto_custom_tool_proto_rawDescGZIP() []byte {
	file_proto_custom_tool_proto_rawDescOnce.Do(func() {
		file_proto_custom_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_custom_tool_proto_rawDesc), len(file_proto_custom_tool_proto_rawDesc)))
	})
	return file_proto_custom_tool_proto_rawDescData
}

var file_proto_custom_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_custom_tool_proto_goTypes = []any{
	(*CustomRequest)(nil),  // 0: custom.CustomRequest
	(*CustomResponse)(nil), // 1: custom.CustomResponse
}
var file_proto_custom_tool_proto_depIdxs = []int32{
	0, // 0: custom.CustomToolService.CustomTool:input_type -> custom.CustomRequest
	1, // 1: custom.CustomToolService.CustomTool:output_type -> custom.CustomResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_custom_tool_proto_init() }
func file_proto_custom_tool_proto_init() {
	if File_proto_custom_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_custom_tool_proto_rawDesc), len(file_proto_custom_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_custom_tool_proto_goTypes,
		DependencyIndexes: file_proto_custom_tool_proto_depIdxs,
		MessageInfos:      file_proto_custom_tool_proto_msgTypes,
	}.Build()
	File_proto_custom_tool_proto = out.File
	file_proto_custom_tool_proto_goTypes = nil
	file_proto_custom_tool_proto_depIdxs = nil
}
