// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/custom_tool.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomToolService_CustomTool_FullMethodName = "/custom.CustomToolService/CustomTool"
)

// CustomToolServiceClient is the client API for CustomToolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomToolServiceClient interface {
	CustomTool(ctx context.Context, in *CustomRequest, opts ...grpc.CallOption) (*CustomResponse, error)
}

type customToolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomToolServiceClient(cc grpc.ClientConnInterface) CustomToolServiceClient {
	return &customToolServiceClient{cc}
}

func (c *customToolServiceClient) CustomTool(ctx context.Context, in *CustomRequest, opts ...grpc.CallOption) (*CustomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CustomResponse)
	err := c.cc.Invoke(ctx, CustomToolService_CustomTool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomToolServiceServer is the server API for CustomToolService service.
// All implementations must embed UnimplementedCustomToolServiceServer
// for forward compatibility.
type CustomToolServiceServer interface {
	CustomTool(context.Context, *CustomRequest) (*CustomResponse, error)
	mustEmbedUnimplementedCustomToolServiceServer()
}

// UnimplementedCustomToolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomToolServiceServer struct{}

func (UnimplementedCustomToolServiceServer) CustomTool(context.Context, *CustomRequest) (*CustomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CustomTool not implemented")
}
func (UnimplementedCustomToolServiceServer) mustEmbedUnimplementedCustomToolServiceServer() {}
func (UnimplementedCustomToolServiceServer) testEmbeddedByValue()                           {}

// UnsafeCustomToolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomToolServiceServer will
// result in compilation errors.
type UnsafeCustomToolServiceServer interface {
	mustEmbedUnimplementedCustomToolServiceServer()
}

func RegisterCustomToolServiceServer(s grpc.ServiceRegistrar, srv CustomToolServiceServer) {
	// If the following call panics, it indicates UnimplementedCustomToolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomToolService_ServiceDesc, srv)
}

func _CustomToolService_CustomTool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomToolServiceServer).CustomTool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomToolService_CustomTool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomToolServiceServer).CustomTool(ctx, req.(*CustomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomToolService_ServiceDesc is the grpc.ServiceDesc for CustomToolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomToolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "custom.CustomToolService",
	HandlerType: (*CustomToolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CustomTool",
			Handler:    _CustomToolService_CustomTool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/custom_tool.proto",
}
